### PR TITLE
Add user-details and enrolments link to AuthContext

### PR DESCRIPTION
**Pull request by nicf82**

### CODE REVIEW

**Comment by roccobruno** [comment]
+1

**Comment by jenshalm** [comment]
This cannot be merged as is. The userDetailsLink property is optional and the macro-based format would fail if it is None (which might be the case for a One Time Login for example).

Please change `userDetailsLink` to `Option[String]`, otherwise LGTM.

**Comment by jenshalm** [comment]
Actually the same is true for the `enrolments` property which is not available for non-GG-accounts. This needs to be `Option[String]`, too.

**Comment by nicf82** [comment]
Cool, ill get that fixed

**Comment by abdusahin** [comment]
@nicf82 released version 5.3.0

**Pull request merged**
