### PR TITLE
[PS] Updated to latest version of http-verbs

### PR DESCRIPTION
**Pull request by andy-gray**
Reverts hmrc/play-authorised-frontend#10
Reverts hmrc/play-authorised-frontend#8
net effect is to reinstate hmrc/play-authorised-frontend#7

### CODE REVIEW

**Comment by andy-gray** [comment]
Don't merge yet - we need to add cred-strength before this change

**Comment by SteveSmithTech** [comment]
@andy-gray @beyond-code-github We need to update this to http-verbs 3.3.0 please, thanks

**Comment by beyond-code-github** [comment]
This possibly can be closed as @andy-gray has made the changes directly

**Comment by andy-gray** [comment]
superseded

**Pull request closed without merging**
